use_frameworks!

platform :ios, '15.6'

target 'Masonry_Example' do
  pod 'Masonry', :path => '../'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.6'
      end
    end
  end
end
